default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: 
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= "#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}_development" %>
  username: <%= "u_#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}" %>
  encoding: utf8mb4
  charset: utf8mb4
  password: <%= "#{ENV['DB_PASS']}" %>

test:
  <<: *default
  database: <%= "#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}_test" %>
  username: <%= "u_#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}" %>
  password: <%= "#{ENV['DB_PASS']}" %>
  encoding: utf8mb4
  collation: utf8mb4_general_ci

production:
  <<: *default
  database: <%= "#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}_production" %>
  username: <%= "u_#{ENV['APP_NAME_UNDER_BAR_AND_UP_TO_14']}" %>
  password: <%= "#{ENV['DB_PASS']}" %>
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: pocketpair-prod.cxexe4gd2td2.ap-northeast-1.rds.amazonaws.com